version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              curl -sL https://git.io/goreleaser |
                bash -s -- --debug --release-notes <(git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^.. | grep -v '^[^ ]* \(Fix\|Merge\|Update\)')
              git clone git@github.com:nem-toolchain/nem-toolchain.github.io.git ../nem-toolchain.github.io
              go get github.com/apex/static/cmd/static-docs && make static && cd ../nem-toolchain.github.io
              git status --verbose
              git add -fA
              git config user.name "${USER_NAME}"
              git config user.email "${USER_EMAIL}"
              git commit --allow-empty -m "Updated by circleci for ${CIRCLE_TAG}"
              git push
            fi

deployment:
  trigger_tag:
    tag: /.*/
